#!/usr/bin/env python3
"""
distill_and_index.py — Brain Lite
===================================

Zero-LLM refresh of the Claude/Memory/twins/*.md twins and Claude/Memory/index.md
for a project brain. Run it from the project root (the folder containing
"Project Documents/" and "Claude/"):

    distill_and_index.exe            # do the work
    distill_and_index.exe --dry-run  # preview only, writes nothing
    distill_and_index.exe --force    # also refresh hand-crafted twins

What it does
-------------
1. Walks "Project Documents/" for source documents (.pptx .docx .xlsx .pdf, plus
   best-effort .vsdx if the optional `vsdx` package is installed). Skips Claude/,
   .claude/, hidden files, ~$ lock files, and *.tmp.
2. For each source file, compares its mtime against the twin's
   `source_modified:` frontmatter stamp (Claude/Memory/twins/<relpath>.md):
     - no twin yet             -> NEW, extract and create it
     - source newer than stamp -> STALE, re-extract and merge it
     - stamp is current        -> untouched
3. Extraction is FAITHFUL, NOT ANALYTICAL: slide-by-slide text + speaker
   notes for pptx, sheet dumps for xlsx, page text for pdf, paragraph/table
   text for docx. Raw text only — no synthesised narrative, no LLM.
4. Twin merge preserves human edits:
     - Extracted text lives inside <!-- AUTO-EXTRACT:BEGIN --> /
       <!-- AUTO-EXTRACT:END --> markers. Only that region is ever replaced.
     - Frontmatter fields added by humans (reuse_notes, etc.) are never touched.
     - A twin with no AUTO-EXTRACT block requires --force before it's touched;
       the fresh extract is appended, nothing existing is removed.
5. After the extraction pass, Memory/index.md is fully regenerated by scanning
   all twins in Memory/twins/ and reading their frontmatter. The index is
   always reproducible from the twins alone — no separate state file.
6. Orphaned twins (source file deleted) are moved to Memory/twins/_archive/
   and dropped from the index.
7. Writes a run report to Memory/.last-distill-report.txt.

Requirements
------------
    pip install python-pptx python-docx openpyxl pypdf
    pip install vsdx   # optional, only needed for .vsdx files
"""

import argparse
import datetime
import io
import os
import re
import sys

# ---------------------------------------------------------------------------
# Config — edit these for your project
# ---------------------------------------------------------------------------

SOURCE_DIR = "Project Documents"      # folder containing all source documents
TWINS_DIR  = "Claude/Memory/twins"   # output folder for markdown twins
INDEX_PATH = "Claude/Memory/index.md" # the searchable index

SOURCE_EXTS = {".pptx", ".docx", ".xlsx", ".pdf"}
OPTIONAL_VSDX_EXT = ".vsdx"
MAX_ROWS_PER_SHEET = 500

# Keyword → tag mapping for auto-tagging. Add terms relevant to your project.
# Example: "integration": "integration", "governance": "governance"
KEYWORD_TAGS: dict[str, str] = {}

AUTO_MARK_BEGIN = (
    "<!-- AUTO-EXTRACT:BEGIN (maintained by distill_and_index.py -- content "
    "below is regenerated from source on every run; do not hand-edit inside "
    "this block, edits will be lost on the next refresh) -->"
)
AUTO_MARK_END = "<!-- AUTO-EXTRACT:END -->"
AUTO_BLOCK_RE = re.compile(re.escape(AUTO_MARK_BEGIN) + r".*?" + re.escape(AUTO_MARK_END), re.DOTALL)
FRONTMATTER_RE = re.compile(r"^---[ \t]*\r?\n(.*?)\n---[ \t]*\r?\n", re.DOTALL)


# ---------------------------------------------------------------------------
# Long-path-safe file I/O (Windows MAX_PATH workaround)
# ---------------------------------------------------------------------------

def _win_prefixed(path: str) -> str:
    ap = os.path.abspath(path)
    if os.name == "nt" and not ap.startswith("\\\\?\\"):
        ap = "\\\\?\\" + ap
    return ap


def safe_read_bytes(path: str) -> bytes:
    try:
        with open(path, "rb") as f:
            return f.read()
    except OSError:
        with open(_win_prefixed(path), "rb") as f:
            return f.read()


def safe_write_text(path: str, text: str) -> None:
    d = os.path.dirname(path)
    if d:
        try:
            os.makedirs(d, exist_ok=True)
        except OSError:
            os.makedirs(_win_prefixed(d), exist_ok=True)
    try:
        with io.open(path, "w", encoding="utf-8") as f:
            f.write(text)
    except OSError:
        with io.open(_win_prefixed(path), "w", encoding="utf-8") as f:
            f.write(text)


def safe_read_text(path: str) -> str:
    try:
        with io.open(path, encoding="utf-8") as f:
            return f.read()
    except OSError:
        with io.open(_win_prefixed(path), encoding="utf-8") as f:
            return f.read()


def safe_mtime_utc(path: str) -> datetime.datetime:
    try:
        ts = os.path.getmtime(path)
    except OSError:
        ts = os.path.getmtime(_win_prefixed(path))
    return datetime.datetime.fromtimestamp(ts, tz=datetime.timezone.utc)


def safe_exists(path: str) -> bool:
    if os.path.exists(path):
        return True
    try:
        return os.path.exists(_win_prefixed(path))
    except OSError:
        return False


def safe_move(src: str, dst: str) -> None:
    d = os.path.dirname(dst)
    if d:
        try:
            os.makedirs(d, exist_ok=True)
        except OSError:
            os.makedirs(_win_prefixed(d), exist_ok=True)
    data = safe_read_bytes(src)
    safe_write_text(dst, data.decode("utf-8", errors="replace"))
    try:
        os.remove(src)
    except OSError:
        os.remove(_win_prefixed(src))


# ---------------------------------------------------------------------------
# Extraction (faithful, mechanical — no interpretation)
# ---------------------------------------------------------------------------

def extract_pptx(raw_bytes: bytes):
    from pptx import Presentation
    prs = Presentation(io.BytesIO(raw_bytes))
    lines = []
    titles = []
    for i, slide in enumerate(prs.slides, 1):
        lines.append("=== SLIDE %d ===" % i)
        title_shape = None
        try:
            title_shape = slide.shapes.title
        except Exception:
            pass
        if title_shape is not None and getattr(title_shape, "has_text_frame", False):
            t = title_shape.text_frame.text.strip()
            if t:
                lines.append("[TITLE] " + t)
                titles.append(t)
        for shape in slide.shapes:
            if shape is title_shape:
                continue
            if getattr(shape, "has_text_frame", False):
                txt = shape.text_frame.text
                if txt and txt.strip():
                    lines.append(txt)
            if getattr(shape, "has_table", False):
                for row in shape.table.rows:
                    lines.append(" | ".join(c.text for c in row.cells))
        try:
            if slide.has_notes_slide and slide.notes_slide.notes_text_frame is not None:
                nt = slide.notes_slide.notes_text_frame.text
                if nt and nt.strip():
                    lines.append("[SPEAKER NOTES] " + nt)
        except Exception:
            pass
        lines.append("")
    header = "**Slide count:** %d\n" % len(prs.slides)
    return header + "\n".join(lines), titles


def extract_xlsx(raw_bytes: bytes):
    from openpyxl import load_workbook
    wb = load_workbook(io.BytesIO(raw_bytes), data_only=True, read_only=True)
    lines = []
    sheet_summaries = []
    for sheet in wb.sheetnames:
        ws = wb[sheet]
        try:
            maxr = ws.max_row or 0
            maxc = ws.max_column or 0
        except Exception:
            maxr = maxc = 0
        sheet_summaries.append("%s (%sx%s)" % (sheet, maxr, maxc))
        lines.append("=== SHEET: %s (rows=%s cols=%s) ===" % (sheet, maxr, maxc))
        count = 0
        for row in ws.iter_rows(values_only=True):
            if row is None:
                continue
            vals = [str(v) for v in row if v is not None]
            if vals:
                lines.append(" | ".join(vals))
                count += 1
            if count >= MAX_ROWS_PER_SHEET:
                lines.append("...(truncated at %d non-empty rows)..." % MAX_ROWS_PER_SHEET)
                break
        lines.append("")
    header = "**Sheets:** " + ", ".join(sheet_summaries) + "\n"
    return header + "\n".join(lines), sheet_summaries


def extract_pdf(raw_bytes: bytes):
    try:
        from pypdf import PdfReader
    except ImportError:
        from PyPDF2 import PdfReader  # type: ignore[no-redef]
    reader = PdfReader(io.BytesIO(raw_bytes))
    lines = []
    empty_pages = 0
    for i, page in enumerate(reader.pages, 1):
        lines.append("=== PAGE %d ===" % i)
        try:
            txt = page.extract_text() or ""
        except Exception:
            txt = ""
        if not txt.strip():
            empty_pages += 1
            lines.append("[no extractable text via pypdf on this page]")
        else:
            lines.append(txt)
        lines.append("")
    n = len(reader.pages)
    header = "**Page count:** %d" % n
    if empty_pages:
        header += "  (**%d page(s) had no extractable text**)" % empty_pages
    header += "\n"
    return header + "\n".join(lines), n


def extract_docx(raw_bytes: bytes):
    from docx import Document
    doc = Document(io.BytesIO(raw_bytes))
    lines = []
    for p in doc.paragraphs:
        if p.text.strip():
            style = (p.style.name if p.style is not None else "") or ""
            if style.lower().startswith("heading"):
                lines.append("### " + p.text)
            else:
                lines.append(p.text)
    for ti, table in enumerate(doc.tables, 1):
        lines.append("\n=== TABLE %d ===" % ti)
        for row in table.rows:
            lines.append(" | ".join(c.text for c in row.cells))
    header = "**Paragraph count:** %d, **Table count:** %d\n" % (len(doc.paragraphs), len(doc.tables))
    return header + "\n".join(lines), len(doc.paragraphs)


def extract_vsdx(raw_bytes: bytes):
    try:
        import vsdx
    except ImportError:
        raise RuntimeError("vsdx package not installed — run `pip install vsdx`")
    import tempfile
    with tempfile.NamedTemporaryFile(suffix=".vsdx", delete=False) as tf:
        tf.write(raw_bytes)
        tmp_path = tf.name
    try:
        vf = vsdx.VisioFile(tmp_path)
        lines = []
        for pi, page in enumerate(vf.pages, 1):
            lines.append("=== PAGE %d: %s ===" % (pi, getattr(page, "name", "")))
            for shape in page.child_shapes:
                text = getattr(shape, "text", "")
                if text and text.strip():
                    lines.append(text.strip())
        header = "**Page count:** %d\n" % len(vf.pages)
        return header + "\n".join(lines), len(vf.pages)
    finally:
        try:
            os.remove(tmp_path)
        except OSError:
            pass


EXTRACTORS = {
    ".pptx": extract_pptx,
    ".xlsx": extract_xlsx,
    ".pdf":  extract_pdf,
    ".docx": extract_docx,
}


# ---------------------------------------------------------------------------
# Mechanical summary + tag derivation
# ---------------------------------------------------------------------------

def derive_tags(text: str) -> list[str]:
    lower = text.lower()
    seen: set[str] = set()
    out: list[str] = []
    for kw, tag in KEYWORD_TAGS.items():
        if kw in lower and tag not in seen:
            seen.add(tag)
            out.append(tag)
    return out[:8]


def mechanical_summary(ext: str, extra) -> str:
    if ext == ".pptx":
        titles = extra[:6]
        s = "PowerPoint deck."
        if titles:
            s += " Slide titles: " + "; ".join(titles)
        return s
    if ext == ".xlsx":
        return "Excel workbook. Sheets: " + ", ".join(str(x) for x in extra[:10])
    if ext == ".pdf":
        return "PDF, %d page(s)." % extra
    if ext == ".docx":
        return "Word document, %d paragraph(s)." % extra
    return "Document."


# ---------------------------------------------------------------------------
# Twin frontmatter helpers
# ---------------------------------------------------------------------------

def read_twin_meta(twin_path: str) -> tuple[str | None, bool]:
    """Return (source_modified_str_or_None, is_script_generated)."""
    try:
        text = safe_read_text(twin_path)
    except OSError:
        return None, False
    m = FRONTMATTER_RE.match(text)
    if not m:
        return None, False
    fm = m.group(1)
    sm = re.search(r"^source_modified:\s*(.+)$", fm, re.MULTILINE)
    gen = re.search(r"^generator:\s*auto-distill-script\s*$", fm, re.MULTILINE)
    return (sm.group(1).strip() if sm else None), bool(gen)


def read_twin_frontmatter(twin_path: str) -> dict[str, str]:
    """Return a dict of frontmatter key→value strings, or {}."""
    try:
        text = safe_read_text(twin_path)
    except OSError:
        return {}
    m = FRONTMATTER_RE.match(text)
    if not m:
        return {}
    result: dict[str, str] = {}
    for line in m.group(1).splitlines():
        if ":" in line:
            k, _, v = line.partition(":")
            result[k.strip()] = v.strip()
    return result


def parse_iso(s: str | None) -> datetime.datetime | None:
    if not s:
        return None
    s = s.strip().strip('"').strip("'")
    if s.lower() == "unknown":
        return None
    if s.endswith("Z"):
        s = s[:-1] + "+00:00"
    try:
        dt = datetime.datetime.fromisoformat(s)
    except ValueError:
        return None
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=datetime.timezone.utc)
    return dt


def _set_frontmatter_field(fm_text: str, key: str, value: str) -> str:
    """Replace an existing `key: value` line, or append one if absent.
    All other lines — including any human-added fields — are left untouched."""
    pattern = re.compile(r"^%s:.*$" % re.escape(key), re.MULTILINE)
    replacement = "%s: %s" % (key, value)
    if pattern.search(fm_text):
        return pattern.sub(lambda _: replacement, fm_text, count=1)
    return fm_text.rstrip("\n") + "\n" + replacement


def build_auto_block(body: str) -> str:
    return AUTO_MARK_BEGIN + "\n\n" + body.strip("\n") + "\n\n" + AUTO_MARK_END


def merge_twin(
    existing_text: str | None,
    source_rel: str,
    mtime_iso: str,
    today: str,
    body: str,
    summary: str,
    tags: list[str],
) -> tuple[str, str]:
    """
    Merge extracted body into a twin, preserving human-contributed frontmatter.
    Returns (new_text, mode) where mode is 'new', 'in-place', or 'appended'.
    """
    new_block = build_auto_block(body)
    tags_str = ", ".join(tags)
    # Guard against newlines / pipes breaking frontmatter / index table
    summary_safe = summary.replace("\n", " ").replace("|", "/")

    if existing_text is None:
        fm = (
            "source: {source}\n"
            "distilled: {distilled}\n"
            "source_modified: {mtime}\n"
            "generator: auto-distill-script\n"
            "summary: {summary}\n"
            "tags: {tags}"
        ).format(source=source_rel, distilled=today, mtime=mtime_iso,
                 summary=summary_safe, tags=tags_str)
        return "---\n%s\n---\n\n%s\n" % (fm, new_block), "new"

    m = FRONTMATTER_RE.match(existing_text)
    if m:
        fm, rest = m.group(1), existing_text[m.end():]
    else:
        fm, rest = "source: %s" % source_rel, existing_text

    fm = _set_frontmatter_field(fm, "distilled", today)
    fm = _set_frontmatter_field(fm, "source_modified", mtime_iso)
    fm = _set_frontmatter_field(fm, "summary", summary_safe)
    fm = _set_frontmatter_field(fm, "tags", tags_str)

    if AUTO_BLOCK_RE.search(rest):
        rest = AUTO_BLOCK_RE.sub(lambda _: new_block, rest, count=1)
        mode = "in-place"
    else:
        rest = rest.rstrip("\n") + "\n\n" + new_block + "\n"
        mode = "appended"

    return "---\n%s\n---\n%s" % (fm, rest), mode


# ---------------------------------------------------------------------------
# Source enumeration (walks Source/ only)
# ---------------------------------------------------------------------------

def iter_source_files(root: str):
    """Yield (rel_to_source, full_abs_path, ext) for every source doc in Source/."""
    source_abs = os.path.join(root, SOURCE_DIR)
    if not os.path.isdir(source_abs):
        return
    exclude = {".claude", "_archive"}
    for dirpath, dirnames, filenames in os.walk(source_abs):
        dirnames[:] = [d for d in dirnames if d not in exclude and not d.startswith(".")]
        for fn in filenames:
            if fn.startswith("~$") or fn.endswith(".tmp") or fn.lower() == "desktop.ini":
                continue
            ext = os.path.splitext(fn)[1].lower()
            if ext not in SOURCE_EXTS and ext != OPTIONAL_VSDX_EXT:
                continue
            full = os.path.join(dirpath, fn)
            rel = os.path.relpath(full, source_abs).replace(os.sep, "/")
            yield rel, full, ext


def is_locked(full_path: str) -> bool:
    d, fn = os.path.split(full_path)
    return safe_exists(os.path.join(d, "~$" + fn))


# ---------------------------------------------------------------------------
# Main extraction pass
# ---------------------------------------------------------------------------

def process_file(root: str, rel: str, full: str, ext: str, force: bool, dry_run: bool, log: dict) -> str:
    """Returns: 'new' | 'merged-in-place' | 'merged-appended' | 'current' |
                'locked' | 'protected' | 'unsupported' | 'error'."""
    twin_rel = rel + ".md"
    twin_abs = os.path.join(root, TWINS_DIR, twin_rel)

    if is_locked(full):
        log["locked"].append(rel)
        return "locked"

    try:
        mtime = safe_mtime_utc(full)
    except OSError as e:
        log["errors"].append((rel, "mtime: %s" % e))
        return "error"

    twin_exists = safe_exists(twin_abs)
    existing_text = None
    if twin_exists:
        stamp_str, is_auto = read_twin_meta(twin_abs)
        stamp_dt = parse_iso(stamp_str)
        is_stale = stamp_dt is None or mtime > stamp_dt + datetime.timedelta(seconds=2)
        if not is_stale:
            return "current"
        if not is_auto and not force:
            log["protected"].append(rel)
            return "protected"
        try:
            existing_text = safe_read_text(twin_abs)
        except OSError as e:
            log["errors"].append((rel, "read twin: %s" % e))
            return "error"

    if ext == OPTIONAL_VSDX_EXT:
        try:
            raw = safe_read_bytes(full)
            body, extra = extract_vsdx(raw)
        except Exception as e:
            log["errors"].append((rel, "extract: %s" % e))
            return "error"
    elif ext in EXTRACTORS:
        try:
            raw = safe_read_bytes(full)
            body, extra = EXTRACTORS[ext](raw)
        except Exception as e:
            log["errors"].append((rel, "extract: %s" % e))
            return "error"
    else:
        log["unsupported"].append(rel)
        return "unsupported"

    mtime_iso = mtime.strftime("%Y-%m-%dT%H:%M:%SZ")
    today = datetime.date.today().isoformat()
    summary = mechanical_summary(ext, extra)
    tags = derive_tags(body)
    new_text, mode = merge_twin(existing_text, rel, mtime_iso, today, body, summary, tags)

    if not dry_run:
        safe_write_text(twin_abs, new_text)

    return "new" if mode == "new" else ("merged-in-place" if mode == "in-place" else "merged-appended")


# ---------------------------------------------------------------------------
# Orphan sweep
# ---------------------------------------------------------------------------

def sweep_orphans(root: str, all_source_rels: set[str], dry_run: bool, log: dict) -> None:
    twins_abs = os.path.join(root, TWINS_DIR)
    archive_abs = os.path.join(twins_abs, "_archive")
    if not os.path.isdir(twins_abs):
        return
    for dirpath, dirnames, filenames in os.walk(twins_abs):
        rel_dir = os.path.relpath(dirpath, twins_abs).replace(os.sep, "/")
        if rel_dir == "_archive" or rel_dir.startswith("_archive/"):
            dirnames[:] = []
            continue
        dirnames[:] = [d for d in dirnames if d != "_archive"]
        for fn in filenames:
            if not fn.endswith(".md"):
                continue
            twin_abs = os.path.join(dirpath, fn)
            twin_rel = os.path.relpath(twin_abs, twins_abs).replace(os.sep, "/")
            source_rel = twin_rel[:-3]  # strip ".md"
            if source_rel in all_source_rels:
                continue
            dest = os.path.join(archive_abs, twin_rel)
            if not dry_run:
                safe_move(twin_abs, dest)
            log["orphans"].append(source_rel)


# ---------------------------------------------------------------------------
# index.md generation — scan all twins and rebuild the table from scratch
# ---------------------------------------------------------------------------

def _escape_cell(s: str) -> str:
    return s.replace("|", "/").replace("\n", " ").strip()


def write_index_md(root: str, dry_run: bool, log: dict) -> None:
    """Scan all (non-archived) twins and regenerate Memory/index.md."""
    twins_abs = os.path.join(root, TWINS_DIR)
    orphan_set = set(log["orphans"])
    rows: list[tuple] = []

    if os.path.isdir(twins_abs):
        for dirpath, dirnames, filenames in os.walk(twins_abs):
            rel_dir = os.path.relpath(dirpath, twins_abs).replace(os.sep, "/")
            if rel_dir == "_archive" or rel_dir.startswith("_archive/"):
                dirnames[:] = []
                continue
            dirnames[:] = [d for d in dirnames if d != "_archive"]
            for fn in filenames:
                if not fn.endswith(".md"):
                    continue
                twin_abs = os.path.join(dirpath, fn)
                twin_rel = os.path.relpath(twin_abs, twins_abs).replace(os.sep, "/")
                source_rel = twin_rel[:-3]  # strip ".md"

                if source_rel in orphan_set:
                    continue

                fm = read_twin_frontmatter(twin_abs)
                file_name = os.path.basename(source_rel)
                summary = fm.get("summary", "")
                tags = fm.get("tags", "")
                modified = fm.get("source_modified", "")
                if modified and "T" in modified:
                    modified = modified.split("T")[0]

                source_path = SOURCE_DIR + "/" + source_rel
                twin_path = TWINS_DIR + "/" + twin_rel
                rows.append((source_rel, file_name, source_path, twin_path, summary, tags, modified))

    rows.sort(key=lambda r: r[0].lower())

    now = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    lines = [
        "# Project Brain — Index",
        "",
        "_Last updated: %s · %d file(s)_" % (now, len(rows)),
        "",
        "To find files: grep this table for a topic, then open the twin at the path in the Twin column.",
        "",
        "| File | Source path | Twin | Summary | Tags | Modified |",
        "|---|---|---|---|---|---|",
    ]
    for _, file_name, source_path, twin_path, summary, tags, modified in rows:
        lines.append("| %s | %s | %s | %s | %s | %s |" % (
            _escape_cell(file_name),
            _escape_cell(source_path),
            _escape_cell(twin_path),
            _escape_cell(summary),
            _escape_cell(tags),
            _escape_cell(modified),
        ))

    index_text = "\n".join(lines) + "\n"
    if not dry_run:
        safe_write_text(os.path.join(root, INDEX_PATH), index_text)

    log["index_total"] = len(rows)


# ---------------------------------------------------------------------------
# Report
# ---------------------------------------------------------------------------

def write_report(root: str, counts: dict, log: dict, dry_run: bool) -> None:
    lines = [
        "=== distill_and_index.py run report ===",
        "Mode: %s" % ("DRY RUN (nothing written)" if dry_run else "LIVE"),
        "Timestamp: %s" % datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "",
        "New twins created:                        %d" % counts["new"],
        "Stale twins refreshed (in place):          %d" % counts["merged-in-place"],
        "Stale twins refreshed (block appended):    %d" % counts["merged-appended"],
        "Already current (skipped):                 %d" % counts["current"],
        "Locked (skipped):                          %d" % len(log["locked"]),
        "Protected hand-crafted (use --force):      %d" % len(log["protected"]),
        "Unsupported format (skipped):              %d" % len(log["unsupported"]),
        "Errors:                                    %d" % len(log["errors"]),
        "Orphaned twins archived:                   %d" % len(log["orphans"]),
        "index.md entries:                          %d" % log.get("index_total", 0),
        "",
    ]
    for label, key in [
        ("-- New twins --",                  "new_files"),
        ("-- Stale (in-place) --",           "merged_in_place_files"),
        ("-- Stale (block appended) --",     "merged_appended_files"),
        ("-- Orphaned (archived) --",        "orphans"),
        ("-- Locked (skipped) --",           "locked"),
        ("-- Protected (use --force) --",    "protected"),
        ("-- Unsupported format --",         "unsupported"),
    ]:
        items = log.get(key, [])
        if items:
            lines.append(label)
            lines.extend("  " + r for r in items)
            lines.append("")
    if log.get("errors"):
        lines.append("-- Errors --")
        lines.extend("  %s: %s" % (r, msg) for r, msg in log["errors"])
        lines.append("")

    report_text = "\n".join(lines)
    print(report_text)
    if not dry_run:
        safe_write_text(os.path.join(root, "Claude", "Memory", ".last-distill-report.txt"), report_text)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    ap.add_argument(
        "--root", default=".",
        help="Project root — the folder containing Source/ and Memory/ (default: current directory)",
    )
    ap.add_argument(
        "--force", action="store_true",
        help="Also refresh hand-crafted twins that have no AUTO-EXTRACT block yet "
             "(the fresh extract is appended; existing content is never removed)",
    )
    ap.add_argument("--dry-run", action="store_true", help="Preview actions, write nothing")
    args = ap.parse_args()

    root = os.path.abspath(args.root)
    source_abs = os.path.join(root, SOURCE_DIR)
    if not os.path.isdir(source_abs):
        print(
            'WARNING: "%s" not found under %s — create it and add your source files first.' % (SOURCE_DIR, root),
            file=sys.stderr,
        )

    log: dict = {
        "locked": [], "protected": [], "unsupported": [], "errors": [], "orphans": [],
        "new_files": [], "merged_in_place_files": [], "merged_appended_files": [],
    }
    counts = {"new": 0, "merged-in-place": 0, "merged-appended": 0, "current": 0}
    all_source_rels: set[str] = set()

    for rel, full, ext in iter_source_files(root):
        all_source_rels.add(rel)
        result = process_file(root, rel, full, ext, args.force, args.dry_run, log)
        if result in counts:
            counts[result] += 1
        if result == "new":
            log["new_files"].append(rel)
        elif result == "merged-in-place":
            log["merged_in_place_files"].append(rel)
        elif result == "merged-appended":
            log["merged_appended_files"].append(rel)

    sweep_orphans(root, all_source_rels, args.dry_run, log)
    write_index_md(root, args.dry_run, log)
    write_report(root, counts, log, args.dry_run)


if __name__ == "__main__":
    main()
